export type TimerMode =
  "POMODORO" | "SHORT_BREAK" | "LONG_BREAK" | "CUSTOM_STOPWATCH";

export interface StudyRoomSession {
  id: string;
  userId: string;
  deckId?: string;
  mode: TimerMode;
  durationSeconds: number;
  startedAt: string;
  completedAt: string;
  cardsReviewedCount: number;
  createdAt: string;
}

export type QuestType =
  | "REVIEW_DUE_CARDS"
  | "STUDY_ANY_SET"
  | "EXPLORE_COMMUNITY_SET"
  | "FOCUS_TIME_TARGET"
  | "FOCUS_45M_TARGET"
  | "UNBROKEN_POMODORO_25M"
  | "PERFECT_TEST_EXAM"
  | "HIGH_SCORE_TEST"
  | "FLAWLESS_SM2_LEARN"
  | "CREATE_STUDY_SET"
  | "COMPLETE_STUDY_MODE"
  | "TAKE_PRACTICE_QUIZ"
  | "STUDY_CLOZE_MODE"
  | "STUDY_WRITE_MODE"
  | "PLAY_MATCH_GAME"
  | "REVIEW_STARRED_CARDS"
  | "STUDY_FLASHCARDS"
  | "AI_GENERATE_CARDS"
  | "CUSTOM_USER_TASK";

export interface DailyQuest {
  id: string;
  userId: string;
  date: string;
  type: QuestType;
  title: string;
  targetCount: number;
  currentCount: number;
  isCompleted: boolean;
  actionUrl?: string;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SRSForecastDay {
  date: string;
  dueCardsCount: number;
  isToday: boolean;
}

export interface StudyRoomDashboardData {
  date: string;
  streak: {
    currentStreak: number;
    longestStreak: number;
    hasStudiedToday: boolean;
  };
  todayStats: {
    focusedMinutes: number;
    cardsReviewed: number;
    dailyTargetMinutes: number;
  };
  quests: DailyQuest[];
  srsForecast: SRSForecastDay[];
}
